Final YML

diff --git a/.github/workflows/build-script-service.yml b/.github/workflows/build-script-service.yml
--- a/.github/workflows/build-script-service.yml
+++ b/.github/workflows/build-script-service.yml
@@ -1,4 +1,4 @@
-name: Build ScriptService
+name: Build ScriptService and Test ScriptService
 on:
   push:
     branches:
@@ -42,3 +42,14 @@ jobs:
 
     - name: 'Run tests on ScriptService project'
       run: dotnet test ${{ env.TEST_PATH }}
+
+    - name: 'Run logger for tests'
+      run: dotnet test ${{ env.TEST_PATH }} --logger "trx;LogFileName=test-results.trx"
+
+    - name: 'Test Report'
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: trx Tests            # Name of the check run which will be created
+        path: ${{ env.TEST_PATH }}/TestResults/test-results.trx      # Path to test results
+        reporter: dotnet-trx
