logfile

diff --git a/.github/workflows/build-user-service.yml b/.github/workflows/build-user-service.yml
--- a/.github/workflows/build-user-service.yml
+++ b/.github/workflows/build-user-service.yml
@@ -43,11 +43,13 @@ jobs:
     - name: 'Run tests on UserService project'
       run: dotnet test ${{ env.TEST_PATH }}
 
-    - name: 'Generate XML Files from tests'
-      run: dotnet test ${{ env.TEST_PATH }} --collect:"XPlat Code Coverage"
+    - name: 'Run logger for tests'
+      run: dotnet test ${{ env.TEST_PATH }} --logger "trx;LogFileName=test-results.trx"
 
-    - name: Publish Unit Test Results
-      uses: EnricoMi/publish-unit-test-result-action@v1.31
-      if: always()
-      with:
-        files: "${{ env.TEST_PATH }}/TestResults/**/coverage.cobertura.xml"
+    - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: JEST Tests            # Name of the check run which will be created
+          path: test-results.trx      # Path to test results
+          reporter: dotnet-trx
